---
title: "NativeMap_Flex24"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll 
    runtime:: shiny
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())


#options(url.method = "wininet")
#options(repos="http://cran.revolutionanalytics.com")
options(repos = c(CRAN = "https://cloud.r-project.org"))

### Load libraries -----
# Will automatically install any libraries it can't find
pkgs <- c("flexdashboard", 
              "shiny", 
              "knitr", 
              "odbc", # pull data from SQL server
              "leaflet", 
              "here",
              "plotly", 
              "tidyverse", 
              "plyr", 
              "sf",
              "readr",
              "magrittr",
              "bslib", 
              "ggplot2",
              "patchwork",
              "leaflet.extras", 
              "lubridate",
              "forcats",
              "httr", # use web services
              # "rgdal", # to use readOGR
              "sp", # transform projections
              "purrr", # for applying functions to dplyr groups
              "dataMaid", # for data checks
              "shinyFiles", # for user to save files in specified location
              "RColorBrewer", # to display brewer palettes
              "shinyjs", # for easy functions that use JavaScript
              "stringr", # to detect text snippets
              "reactable",
              "reactablefmtr",
              "base", 
              "htmltools", 
              "ggthemes",
              "data.table", # for fast lag calcs
              "DT", # for interactive tables
              "cowplot", # to get legends from plots
              "crosstalk", # for SharedData
              "gridExtra", # for arranging plots and adding plot annotations (ggplotly can't do captions or subtitles)
              "RgoogleMaps", # for MaxZoom & MinZoom
              "leaflet.minicharts") # for pie charts in leaflet maps


installed_pkgs <- pkgs %in% installed.packages()
if (length(pkgs[!installed_pkgs]) > 0) install.packages(pkgs[!installed_pkgs],dep=TRUE) 
lapply(pkgs, library, character.only = TRUE)

invisible(lapply(pkgs, library, character.only = TRUE))

options(shiny.maxRequestSize=60*1024^2) #increase the file upload limit to 90MB.

rv <- reactiveValues(SeedlingSapling = NULL, SpeciesDiversity = NULL, Tree = NULL, CanopyCover = NULL, StandHeight = NULL, Genus = NULL, LatLong = NULL, Species_Cover = NULL, Cover_Class = NULL, Exotics = NULL, CWD = NULL, BroadGroup = NULL, CycleNumber = NULL)

temp_rv <- shiny::reactiveValues(
  df_mapwide = NULL, 
  columns_to_include = NULL,
  color_palette = NULL, 
  bc = NULL, 
  ec = NULL, 
  nc = NULL,
  map_nativesequence = NULL
)
```

```{r message = FALSE, results = FALSE, echo = FALSE}
#reading in csvs

trees <- read_csv(here::here("output", "CUPN_TreeBasics.csv")) #NEWNEW cycle tree basics
seedlingsapling <- read_csv(here::here("output", "CUPN_SeedlingSapling.csv")) #NEWNEW cycle seedling sapling
broadgroup <- read_csv(here::here("output", "CUPN_BroadGroup.csv")) #used to be broadgroup
speciesrich <- read_csv(here::here("output", "CUPN_SpeciesDiversity.csv"))
location <- read_csv(here::here("output", "Location_Table2.csv")) #let's just call this LOCATION
canopycover <- read_csv(here::here("output", "CUPN_CanopyCover.csv"))
genus_group <- read_csv(here::here("output", "Genus_grouping.csv"))
events <- read_csv(here::here("output", "CUPN_EventTable2.csv"))
shapefile <- st_read(here::here('./cupn_shapefile/CUPN.shp'))
speciescover <- read_csv(here::here("output", "CUPN_SpeciesCover.csv"))
taxa <- read_csv(here::here("output", "TaxaTable.csv"))
coverclass <- read_csv(here::here("output", "CoverClass.csv"))

mp_compboundary <- st_transform(shapefile, crs = 4326)

```

```{r functions}
### Functions-----

#rounding function 
#stick to a certain function naming rule
round_df <- function(x, digits) {
    numeric_columns <- sapply(x, mode) == 'numeric'
    x[numeric_columns] <-  round(x[numeric_columns], digits)
    x
}

options(scipen=999)

#keeping only first letter of character
makeInitials <- function(charVec) {
  make.unique(vapply(strsplit(toupper(charVec), " "), 
                     function(x) paste(substr(x, 1, 1), collapse = ""), 
                     vector("character", 1L)))
}

#color palettes
Okabe_Ito <- c("#E69F00", "#56B4E9", "#009E73", '#CC6677',"#F0E442", "#0072B2", "#D55E00", 
               "#CC79A7", "#000000",'#DDDDDD', '#EE6678', '#99DDFF', 
               '#BBCC33', '#332288', '#882255', '#FFAABB')

okabe_ito <- c( "#0072B2", "#D55E00", 
               "#CC79A7", "#000000",  '#CC6677', '#BBCC33', '#99DDFF', 
                '#332288', '#882255', '#FFAABB', "#E69F00", "#56B4E9", "#009E73", "#F0E442")

viridis <- c("#fde725", "#5ec962", "#21918c","#3b528b","#440154")

jane <- c('#a5cee2', '#1f78b4', '#b2df8a', '#e7298b', '#33a02b', '#997dd4', '#000000', '#fc9a99','#e21a1c', '#fdbe6f', '#ff7f00', '#9c9c9c', '#cab2d6', '#6a3d9a', '#feff99', '#b15929')

# function to group by a plot, year and find the count of n
makefun <- function(data) {
  data %>% 
  dplyr::group_by(Plot_Code, Sample_Year) %>%
  dplyr::summarize(n())
  
}
##### css functions
integer_columns <- function(maxWidth = 60, ...) {
  colDef(maxWidth = maxWidth, align = "center",...)
}

with_tooltip <- function(value, tooltip) {
  tags$abbr(style = "text-decoration: underline; text-decoration-style: dotted; cursor: help", title = tooltip, value)
}

# lists for organizing column orders
positions <- c("Tree", "Sapling", "Seedling")

col_group <- c("Plot_Code", "Plant_Code", "Start_Date", "Sample_Year", "Event_ID")

#Needs to get ride of Network, Park, and Subunit, Change Start_Date to Sample Date?
common_columns <- c("Network_Code", "Park_Code", "Subunit_Code", "Plot_Code", "Start_Date", "Event_Type_Name", "Sample_Year") 

remove_habcolumns <- c("Fit", "Confidence", "Sample_Year", "Event_ID", "Start_Date", "Plot_Code") 
```

```{r}
func_processdata <- function(df, growth_form) {
  df %>%
    dplyr::mutate(Start_Date = as.Date(lubridate::mdy_hm(Start_Date)),
                  Sample_Year = as.factor(Sample_Year),
                  Growth_Form = growth_form) # %>%
    #as.data.frame()#
}


func_seedsap <- function(df, form_col, total_col) {
  df %>%
    replace(is.na(.), 0) %>%
    dplyr::group_by(Plot_Code, Start_Date, Event_ID, Sample_Year, Plant_Code, Growth_Form = form_col) %>%
    dplyr::summarise(Count = sum({{total_col}}, na.rm = TRUE)) %>%
    ungroup()
}

```

```{r}

df_genus <- taxa %>% 
  dplyr::select(Plant_Code, Genus) 

broadgroup <- func_processdata(broadgroup, NA)

df_events <- func_processdata(events, NA)

all_events <- df_events %>%
  left_join(broadgroup) %>%
  dplyr::filter(Event_Type != "QA/QC")%>%
  left_join(location %>% dplyr::select(Network_Code, Park_Code, Subunit_Code, Plot_Code), by = "Plot_Code")

df_trees <- func_processdata(trees, "Tree") %>%
  dplyr::filter(Status_Name == "Live Tree") %>%
  dplyr::mutate(BA_ha = ((pi * DBH^2) / 40000) / 0.04)

df_seedsap <- func_processdata(seedlingsapling, NA)

 # new code for woody map _flex24
location %<>%
    dplyr::select(Park_Code, Subunit_Code, Plot_Code, Latitude, Longitude)

genus_grouping <-  if (!exists("genus_group")) {
  genus_grouping <- NULL
  } else { 
  genus_grouping <- genus_group
  }

```




```{r}

#list of high priority species 
nonnative_hp <- taxa %>%
  dplyr::filter(Flag_High_Priority_Exotic == "High") %>%
  pull(Plant_Code)

nonnative <- taxa %>%
  dplyr::filter(Nativity == "Non_Native")

#joining species richness dataset with taxonomic designations
df_speciesrich <- speciesrich %>%
  left_join(select(taxa, Plant_Code, Network_Scientific_Name, Nativity, Genus, Growth_Form, Flag_High_Priority_Exotic), by = "Plant_Code")

#selecting only "exotic species" and designating them as high or low in a column called non-native

species_exotics <- df_speciesrich %>%
  dplyr::filter(Nativity == "Non-Native") %>% 
  dplyr::mutate(Flag_High_Priority_Exotic = replace_na(Flag_High_Priority_Exotic, "Low"))

```


```{r}
observeEvent(eventExpr = input$button_UpdateNativeTreeCompMap, {
  shiny::req(!is.null(input$mp_nativeunit), !is.null(input$mp_nativeyr), !is.null(mp_compboundary), !is.null(location), !is.null(df_speciesrich), !is.null(speciescover), !is.null(taxa), !is.null(input$mp_nativegroup), !is.null(species_exotics), !is.null(input$mp_nativecycle), !is.null(all_events))
  
# input values
# input <- list()
# input$mp_nativeunit <- "BIRT"
# input$mp_nativeyr <- "2011"
# input$mp_nativegroup <- "Genus"
# input$mp_nativecycle <- "Sample_Year"
  
nmap_spgroup <- input$mp_nativegroup

constancy_native <- speciescover %>%
  dplyr::left_join(select(taxa, Plant_Code, Genus)) %>%
    dplyr::select(Plot_Code, Start_Date, Plant_Code, !!as.name(nmap_spgroup), Cover_Class, !!as.name(input$mp_nativecycle)) 

# %>%
#     dplyr::left_join(coverclass)

df_complatlong <- location %>% 
  dplyr::select(-Park_Code) %>% #for some reason people want park code hmm can't do that for mapping smh
  dplyr::mutate(Plot_Num = substr(Plot_Code, 5, 10))

species_exoticsnum <- df_speciesrich %>%
  dplyr::filter(Nativity == "Native" | 
                Nativity == "Non-Native") %>%
  dplyr::group_by(Plot_Code, Event_ID, !!as.name(input$mp_nativecycle), Nativity) %>%
  dplyr::summarise(Exotic_count = n()) %>%
  ungroup()


df_numexotics <- species_exotics %>%
   dplyr::mutate(Network_Scientific_Name2 = Network_Scientific_Name, 
                Taxa2 = !!as.name(input$mp_nativegroup),
                Network_Scientific_Name = case_when(Flag_High_Priority_Exotic == "High" ~  as.character(Network_Scientific_Name), TRUE ~ "Other")) %>%
  dplyr::mutate(!! input$mp_nativegroup := case_when(Flag_High_Priority_Exotic == "High" ~ !!as.name(input$mp_nativegroup), TRUE ~ "Other")) %>%
  dplyr::group_by(Plot_Code, Event_ID,
                  Network_Scientific_Name, ########hrmmmmmm what does this mean should it be binned to the network level or the genus level ... confusion hmmmmmm I guess actually not since we can bin to other groupings and that makes the other 
                  !!as.name(nmap_spgroup),
                  !!as.name(input$mp_nativecycle)) %>%
  dplyr::summarise(Num = n()) %>%
  ungroup()

expanded <- df_numexotics %>%
  dplyr::select(Plot_Code, Event_ID, !!as.name(input$mp_nativecycle)) %>%
  dplyr::group_by(Plot_Code, Event_ID, !!as.name(input$mp_nativecycle)) %>%
  distinct() %>%
  ungroup() %>%
  dplyr::mutate(!! input$mp_nativegroup := as.factor("Other"), #####NEW SYNTAX HELPFUL
                Network_Scientific_Name = as.factor("Other")) %>%
  cbind(Num = 0)

df_numexotics <- dplyr::full_join(df_numexotics, expanded) 

## NOW WE GROUP BY THE NATIVE GROUP
df_numexotics %<>%
   dplyr::group_by(Plot_Code, Event_ID,
                  !!as.name(input$mp_nativegroup), !!as.name(input$mp_nativecycle)) %>%
  dplyr::summarise(Num = sum(Num)) %>%
  ungroup()

#zoom zoom
mp_nativezoom <- df_complatlong %>%
  dplyr::filter(Subunit_Code == input$mp_nativeunit)


map_nativesequence <- all_events %>%
  dplyr::filter(Subunit_Code == input$mp_nativeunit) %>%
  dplyr::filter(!!as.name(input$mp_nativecycle) == input$mp_nativeyr) %>%
  pull(Event_ID)

rv$map_nativesequence <- map_nativesequence

#filters and widens with the raw numbers 
nonnativeprop <- species_exoticsnum %>%
  dplyr::filter(Event_ID %in% map_nativesequence) %>%
  # dplyr::filter(Subunit_Code == input$mp_nativeunit) %>%
  dplyr::filter(!!as.name(input$mp_nativecycle) %in% input$mp_nativeyr) %>%
  pivot_wider(names_from = Nativity, 
              values_from = Exotic_count) %>%
  left_join(df_complatlong) %>%
  dplyr::filter(!is.na(Latitude)) %>%
  dplyr::filter(!is.na(Longitude)) %>%
  replace(is.na(.), 0) 

rv$ec = leaflet::leaflet(data = mp_compboundary) %>%
  addTiles() %>%
  addPolygons(data = mp_compboundary, color = ~ "black") %>%
  addMinicharts(nonnativeprop$Longitude,
                  nonnativeprop$Latitude, # time = as.character(rv$native_comp$Year),
                  chartdata = dplyr::select(nonnativeprop, -c(Subunit_Code, Event_ID, Plot_Num, Plot_Code, all_of(input$mp_nativecycle), Latitude, Longitude)), 
                  type = "pie",
                  width = 40,
                  col = Okabe_Ito,
                  showLabels = F
    ) %>%
    addLabelOnlyMarkers(df_complatlong$Longitude,
                      df_complatlong$Latitude, 
                      label =  df_complatlong$Plot_Num,
                      labelOptions = labelOptions(noHide = T, direction = 'top', textOnly = T, style=list('color'="#000000", 'fontSize'="15px"))) %>%
        addScaleBar(position = "bottomright") %>%
    fitBounds(min(mp_nativezoom$Longitude), min(mp_nativezoom$Latitude), max(mp_nativezoom$Longitude), max(mp_nativezoom$Latitude)) 


############# nwo now now nwownw 


native_comp <- df_numexotics %>%
  dplyr::filter(Event_ID %in% map_nativesequence) %>%
  # dplyr::filter(Subunit_Code == input$mp_nativeunit) %>%
  dplyr::filter(!!as.name(input$mp_nativecycle) %in% input$mp_nativeyr)


# rv$native_comp <- native_comp

# average plot cover that was used to be representative of the size of the pie chart
# native_comptest <- native_comp %>%
#   dplyr::left_join(constancy_native) %>%
#   dplyr::group_by(Plot_Code, !!as.name(input$mp_nativecycle)) %>%
#   dplyr::summarise(avg_plotcover = mean(Geometric_Mean, na.rm = TRUE))
  
# pivot that shiii wider
native_comp <- native_comp %>%
   pivot_wider(names_from = !!as.name(input$mp_nativegroup), 
               values_from = Num) %>%
  dplyr::select(sort(names(.))) %>%
  dplyr::select(-Other, everything()) 
# %>%
#   dplyr::left_join(native_comptest)

# joining the park, subunit, plot, lat, and long  
native_comp <- left_join(native_comp, df_complatlong, by = "Plot_Code")

####################################################################################

native_comp <- native_comp %>%
  dplyr::filter(!is.na(Latitude)) %>%
  dplyr::filter(!is.na(Longitude)) %>%
  replace(is.na(.), 0) 
#why did i have an rv$native comp here??




rv$nc = leaflet::leaflet(data = mp_compboundary) %>%
  addTiles() %>%
  addPolygons(data = mp_compboundary, color = ~ "black") %>%
  addMinicharts(native_comp$Longitude,
                  native_comp$Latitude, # time = as.character(rv$native_comp$Year),
                  chartdata = dplyr::select(native_comp, -c(Event_ID, Subunit_Code, Plot_Num, Plot_Code, all_of(input$mp_nativecycle), Latitude, Longitude)), 
                  type = "pie",
                  width = 40, # sqrt(native_comp$avg_plotcover) * 15,
                  col = Okabe_Ito,
                  showLabels = F
    ) %>%
    addLabelOnlyMarkers(df_complatlong$Longitude,
                      df_complatlong$Latitude, 
                      label =  df_complatlong$Plot_Num,
                      labelOptions = labelOptions(noHide = T, direction = 'top', textOnly = T, style=list('color'="#000000", 'fontSize'="15px"))) %>%
        addScaleBar(position = "bottomright") %>%
    fitBounds(min(mp_nativezoom$Longitude), min(mp_nativezoom$Latitude), max(mp_nativezoom$Longitude), max(mp_nativezoom$Latitude)) 


# cat("Line55")
# saveRDS(isolate(reactiveValuesToList(input)), paste0("nc_input.RDS"))
# saveRDS(isolate(reactiveValuesToList(rv)), paste0("nc_rv.RDS"))

})

```


Sp. Native Maps {data-width=350}
=======================================================================
###

*<font size="3"> This map shows pie charts of genera for each plot containing data in a given year and park subunit.  * </font>
*<font size="3"> De-select "marker' and select "marker" again to be able to click on a plot and see the corresponding proportional stacked bar chart. In order to see the raw numbers on the plot, unselect "marker" and click on the pie chart itself. * </font>

####
```{r native map input, echo = FALSE}
div(
  style = "display: flex; flex-wrap: wrap;",
  
div(style = "margin-top: 10px; margin-right: 30px; align-self: center; ",
actionButton("button_UpdateNativeTreeCompMap", "Update Map")
), 

div(style = "margin-top: 10px;", 

renderUI({
     shiny::req(!is.null(location))
    
  selectInput(
    "mp_nativeunit",
    label = strong("Select a Unit: "),
    choices = sort(unique(location$Subunit_Code)),
    selected = switch(is.null(input$mp_nativeunit)+1, input$mp_nativeunit, "BIRT")
    )
})
), 

div(style = "margin-top: 10px;", 
    
    renderUI({
  shiny::req(!is.null(speciescover))
  
  if ("Cycle" %in% names(speciescover)) {
    conditionalPanel(
    condition = "(Cycle %in% names(tree_basics))",
    selectInput("mp_nativecycle", 
                label = strong("Select Temporal Grouping:"), 
                choices = c("Year" = "Sample_Year", "Cycle") ))
    
    } else {
      selectInput("mp_nativecycle", 
                label = strong("Select Temporal Grouping:"), 
                choices = c("Year" = "Sample_Year"), 
                selected = c("Year" = "Sample_Year"))
      }
})
),


div(style = "margin-top: 10px;", 
renderUI({
  shiny::req(!is.null(all_events), !is.null(input$mp_nativeunit), !is.null(speciescover))
  
  if (input$mp_nativecycle == "Sample_Year") { 
  
    nativeyr <- all_events %>%
    filter(Subunit_Code == input$mp_nativeunit) %>%
    distinct(Sample_Year) %>%
    pull(.)
    
selectInput(
  "mp_nativeyr", 
  label = strong("Select Year: "), 
  choices = sort(nativeyr), 
  selected = min(as.numeric(as.character(nativeyr)))
) 
  } else {
    
    nativecycle <- all_events %>%
    filter(Subunit_Code == input$mp_nativeunit) %>%
    distinct(Cycle) %>%
    pull(.)
    
    selectInput(
  "mp_nativeyr", 
  label = strong("Select Cycle: "), 
  choices = sort(unique(nativecycle)), 
  selected = min(nativecycle)
    )
    
  }
})
),

div(style = "margin-top: 10px;", 

renderUI({
  shiny::req(!is.null(taxa))
  
  nmap_sp <- names(taxa)[! names(taxa) %in% c("Plant_Code", "Network_Scientific_Name")]
  
  selectInput(
    "mp_nativegroup", 
    label = strong("Select Species Grouping: "), 
    choices = "Genus", 
    selected = "Genus"
  
  )
})
)
)

```

Row
-----------------------------------------------------------------------
###
```{r native map 2}
output$nativeleaflet <- renderLeaflet({
  shiny::req(!is.null(rv$nc)) 
  rv$nc
  })

leafletOutput("nativeleaflet", height = "95vh")
```

###
```{r}

output$nativeecleaflet <- renderLeaflet({
  shiny::req(!is.null(rv$ec)) 
  rv$ec
  })

leafletOutput("nativeecleaflet", height = "95vh")

```

