---
title: "WoodyMap_Flex24"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r}
#reading in csvs

trees <- read_csv(here::here("output", "CUPN_TreeBasics.csv")) #NEWNEW cycle tree basics
seedlingsapling <- read_csv(here::here("output", "CUPN_SeedlingSapling.csv")) #NEWNEW cycle seedling sapling
broadgroup <- read_csv(here::here("output", "CUPN_BroadGroup.csv")) #used to be broadgroup
# species_rich <- read_csv(here::here("Data_In","SpeciesDiversity_LongFormat_20230421.csv")) #waiting on new data from Tim
genus <- read_csv(here::here("output", "TaxaTable.csv"))
location <- read_csv(here::here("output", "Location_Table.csv")) #let's just call this LOCATION
canopycover <- read_csv(here::here("output", "CUPN_CanopyCover.csv"))
genus_grouping <- read_csv(here::here("output", "Genus_grouping.csv"))
shapefile <- st_read(here::here('./cupn_shapefile/CUPN.shp'))
  
mp_compboundary <- st_transform(shapefile, crs = 4326)

```


```{r functions}
### Functions-----

#rounding function 
#stick to a certain function naming rule
round_df <- function(x, digits) {
    numeric_columns <- sapply(x, mode) == 'numeric'
    x[numeric_columns] <-  round(x[numeric_columns], digits)
    x
}

options(scipen=999)

#keeping only first letter of character
makeInitials <- function(charVec) {
  make.unique(vapply(strsplit(toupper(charVec), " "), 
                     function(x) paste(substr(x, 1, 1), collapse = ""), 
                     vector("character", 1L)))
}

#color palettes
Okabe_Ito <- c("#E69F00", "#56B4E9", "#009E73", '#CC6677',"#F0E442", "#0072B2", "#D55E00", 
               "#CC79A7", "#000000",'#DDDDDD', '#EE6678', '#99DDFF', 
               '#BBCC33', '#332288', '#882255', '#FFAABB')

okabe_ito <- c( "#0072B2", "#D55E00", 
               "#CC79A7", "#000000",  '#CC6677', '#BBCC33', '#99DDFF', 
                '#332288', '#882255', '#FFAABB', "#E69F00", "#56B4E9", "#009E73", "#F0E442")

viridis <- c("#fde725", "#5ec962", "#21918c","#3b528b","#440154")

jane <- c('#a5cee2', '#1f78b4', '#b2df8a', '#e7298b', '#33a02b', '#997dd4', '#000000', '#fc9a99','#e21a1c', '#fdbe6f', '#ff7f00', '#9c9c9c', '#cab2d6', '#6a3d9a', '#feff99', '#b15929')

# function to group by a plot, year and find the count of n
makefun <- function(data) {
  data %>% 
  dplyr::group_by(Plot_Code, Year) %>%
  dplyr::summarize(n())
  
}
##### css functions
integer_columns <- function(maxWidth = 60, ...) {
  colDef(maxWidth = maxWidth, align = "center",...)
}

with_tooltip <- function(value, tooltip) {
  tags$abbr(style = "text-decoration: underline; text-decoration-style: dotted; cursor: help", title = tooltip, value)
}

# lists for organizing column orders
positions <- c("Tree", "Sapling", "Seedling")

col_group <- c("Plot_Code", "Plant_Code", "Start_Date", "Sample_Year", "Event_ID")

#Needs to get ride of Network, Park, and Subunit, Change Start_Date to Sample Date?
common_columns <- c("Network_Code", "Park_Code", "Subunit_Code", "Plot_Code", "Start_Date", "Event_Type_Name", "Year") 
```

```{r}

df_genus <- genus %>% 
  dplyr::select(Plant_Code, Genus) 

func_processdata <- function(df, growth_form) {
  df %>%
    dplyr::mutate(Start_Date = as.Date(lubridate::mdy_hm(Start_Date)),
                  Sample_Year = as.factor(Sample_Year),
                  Growth_Form = growth_form)
}

df_trees <- func_processdata(trees, "Tree") %>%
  dplyr::filter(Status_Name == "Live Tree") %>%
  dplyr::mutate(BA_ha = ((pi * DBH^2) / 40000) / 0.04)

df_seedsap <- func_processdata(seedlingsapling, NA)

 # new code for woody map _flex24
location %<>%
    dplyr::select(Park_Code, Subunit_Code, Plot_Code, Latitude, Longitude)


df_treedivsum <- df_trees %>% #----------Summing basal area per growth form, year, plot, and subunit 
  dplyr::group_by(Plot_Code, Start_Date, Event_ID, Sample_Year, Growth_Form) %>%
  dplyr::summarise(Sum = sum(BA_ha)) %>%
  tidyr::pivot_longer(cols = Sum, 
                      names_to = "Plant_Code", 
                      values_to = "Count")
  # tidyr::pivot_longer(cols = Sum, 
  #                     names_to = "Genus", 
  #                     values_to = "Count")   old code when GENUS was still included in the input data
  # is there a better way? Should we keep df_treediv and df_treedivsum separate?

df_treediv <- df_trees %>% #----------finding raw count of live trees per growth form, year, plot, and subunit - are we not taking genus into account?? just raw numbers?? for us just plant_code which DOOESSS reduce the amount of observatiosn not as much as if by genus hmmmmmmmmmmmmmmmm
  dplyr::group_by(Plot_Code, Start_Date, Event_ID, Sample_Year, Plant_Code, Growth_Form) %>%
  dplyr::summarize(Count = n()) %>%
  ungroup() %>%
  full_join(df_treedivsum)


func_seedsap <- function(df, form_col, total_col) {
  df %>%
    replace(is.na(.), 0) %>%
    dplyr::group_by(Plot_Code, Start_Date, Event_ID, Sample_Year, Plant_Code, Growth_Form = form_col) %>%
    dplyr::summarise(Count = sum({{total_col}}, na.rm = TRUE)) %>%
    ungroup()
}

df_mapsapdiv <- func_seedsap(df_seedsap %>% dplyr::mutate(Growth_Form = "Sapling"), "Sapling", Sapling_Total)

df_mapsapsum <- df_seedsap %>%
  dplyr::mutate(
    Growth_Form = "Sapling",
    Sapling01_BA =  (0.00007854 * (0.5)^2 ) * Sapling_0_1_DBH,
    Sapling12h_BA = (0.00007854 * (1.75)^2 ) * Sapling_1_2half_DBH,
    Sapling2h5_BA = (0.00007854 * (3.25)^2 ) * Sapling_2half_5_DBH ,
    Sapling510_BA = (0.00007854 * (7.5)^2 ) * Sapling_5_10_DBH
  ) %>%
  dplyr::group_by(Plot_Code, Start_Date, Event_ID, Sample_Year, Growth_Form) %>%
  dplyr::summarise(
    Sum = sum(Sapling01_BA, Sapling12h_BA, Sapling2h5_BA, Sapling510_BA, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  tidyr::pivot_longer(
    cols = Sum,
    names_to = "Plant_Code",
    values_to = "Count"
  )

df_sapdiv <- dplyr::full_join(df_mapsapdiv, df_mapsapsum) #-------joining count and basal area calculations for saplings

df_mapseeddiv <- func_seedsap(df_seedsap %>% dplyr::mutate(Growth_Form = "Seedling"), "Seedling", Seedling_Total)

df_mapseedsum <- df_mapsapsum %>%
  dplyr::mutate(Growth_Form = "Seedling", 
                Count = 50) # so much easier lol

df_seeddiv <- dplyr::full_join(df_mapseeddiv, df_mapseedsum) 


df_spdiv <-  Reduce(function (...) { merge(..., all = TRUE) },  #full join idk why I can't just do a regular left join....
                        list(df_treediv, df_sapdiv, df_seeddiv))
#### end of code within the flexdashboard
```

```{r TRYING TO SEE FOR PLANT CODE}
#### OBSERVE EVENT
    
input <- list()
input$size_class = "Sapling"
input$map_year <- "2017"
input$map_subunit <- "COWP" #check
input$map_spgroup <- "Genus"


#################### THIS WOULD HAVE TO BE A POTENTIAL CHANGE TO THIS PAGE.....EITHER THIS OR WOULD HAVE TO TAKE THE 
df_treesunits <- df_trees %>%
  dplyr::filter(str_detect(Plot_Code, input$map_subunit),
                Sample_Year %in% input$map_year) %>%
  left_join(df_genus) %>%
  dplyr::group_by(!!as.name(input$map_spgroup)) %>%     #either group by plant code or by a group of selected genuses????
  dplyr::summarize(tree_obs = n()) %>%
  ungroup() %>%
  top_n(7, tree_obs) %>%
  droplevels(.)


woodymptop_species <- df_treesunits %>%
                        distinct(!!as.name(input$map_spgroup)) %>%  # use !!as.name to refer to the column
                        pull()

woodymptop_species <- as.character(c(as.character(woodymptop_species), "Other", "Sum"))
####################


genus_group <- genus_grouping %>%
  select(!!as.name(input$map_spgroup), everything())

woodymptop_species <- unique(genus_group[[input$map_spgroup]])


spdiv <- df_spdiv %>%
  left_join(df_genus) %>%
  dplyr::mutate(Subunit_Code = substr(Plot_Code, 1, 4),
                Plant_Code = as.factor(Plant_Code)) %>%
  dplyr::mutate(Plot_Genus = forcats::fct_other(.[[input$map_spgroup]],
                                                   keep = woodymptop_species, ### this could be an input
                                                   other_level = 'Other')) %>%
  dplyr::mutate(Plot_Genus = as.character(Plot_Genus)) %>%
  dplyr::mutate(Genus = case_when(
    Plant_Code == "Sum" ~ "Sum",
    TRUE ~ Genus)) %>%
  dplyr::mutate(Plot_Genus = case_when(
    Plant_Code == "Sum" ~ "Sum",
    TRUE ~ Plot_Genus)
  ) %>%
  dplyr::mutate(Plot_Genus = as.factor(Plot_Genus)) %>%
  dplyr::group_by(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, Plot_Genus) %>%
  dplyr::summarise(Count = sum(Count)) %>%
  ungroup()

# rv$spcomp <- spcomp # save spdiv is the equivalent into a reactive format
# rv$spdiv <- spdiv

df_mapwide <- spdiv %>%
  tidyr::pivot_wider(
    names_from = Plot_Genus,
    values_from = Count) %>%
  dplyr::select(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, sort(setdiff(tidyselect::peek_vars(), "Other")), Other)


df_mapspdiv  <- df_mapwide %>%
  dplyr::filter(Growth_Form == input$size_class)

  # dplyr::select(-Other, Subunit_Code, Plot_Code, Sample_Year, sort(tidyselect::peek_vars())) # I'm worried about the select -Other
```

```{r LOOKING AT THIS OBSERVE EVENT AT GENUS this works}
#### OBSERVE EVENT
    
# input <- list()
# input$size_class = "Sapling"
# input$map_year <- "2017"
# input$map_subunit <- "COWP" #check
# input$map_spgroup <- "Genus"
# 
# 
# 
# df_treesunits <- df_trees %>%
#   dplyr::filter(str_detect(Plot_Code, input$map_subunit),
#                 Sample_Year %in% input$map_year) %>%
#   left_join(df_genus) %>%
#   dplyr::group_by(!!as.name(input$map_spgroup)) %>%     #either group by plant code or by a group of selected genuses????
#   dplyr::summarize(tree_obs = n()) %>%
#   ungroup() %>%
#   top_n(7, tree_obs) %>%
#   droplevels(.)
# 
# 
# woodymptop_species <- df_treesunits %>%
#                         distinct(!!as.name(input$map_spgroup)) %>%  # use !!as.name to refer to the column
#                         pull()
# 
# woodymptop_species <- as.character(c(as.character(woodymptop_species), "Other", "Sum"))
# 
# spdiv <- df_spdiv %>%
#   left_join(df_genus) %>%
#   dplyr::mutate(Subunit_Code = substr(Plot_Code, 1, 4)) %>%
#   dplyr::mutate(Plot_Genus = forcats::fct_other(Genus,
#                                                    keep = woodymptop_species, ### this could be an input
#                                                    other_level = 'Other')) %>%
#   dplyr::mutate(Plot_Genus = as.character(Plot_Genus)) %>%
#   dplyr::mutate(Genus = case_when(
#     Plant_Code == "Sum" ~ "Sum",
#     TRUE ~ Genus )) %>%
#   dplyr::mutate(Plot_Genus = case_when(
#     Plant_Code == "Sum" ~ "Sum",
#     TRUE ~ Plot_Genus)
#   ) %>%
#   dplyr::mutate(Plot_Genus = as.factor(Plot_Genus)) %>%
#   dplyr::group_by(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, Plot_Genus) %>%
#   dplyr::summarise(Count = sum(Count)) %>%
#   ungroup()
# 
# # rv$spcomp <- spcomp # save spdiv is the equivalent into a reactive format
# # rv$spdiv <- spdiv
# 
# df_mapwide <- spdiv %>%
#   tidyr::pivot_wider(
#     names_from = Plot_Genus,
#     values_from = Count) %>%
#   dplyr::select(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, sort(setdiff(tidyselect::peek_vars(), "Other")), Other)
# 
#   # dplyr::select(-Other, Subunit_Code, Plot_Code, Sample_Year, sort(tidyselect::peek_vars())) # I'm worried about the select -Other
# 
# df_mapspdiv  <- df_mapwide %>%
#    dplyr::filter(Growth_Form == input$size_class)

```

```{r LOOKING AT THIS OBSERVE EVENT AT GENUS this works}
#### OBSERVE EVENT
    
# input <- list()
# input$size_class = "Sapling"
# input$map_year <- "2017"
# input$map_subunit <- "COWP" #check
# input$map_spgroup <- "Genus"
# 
# 
# 
# df_treesunits <- df_trees %>%
#   dplyr::filter(str_detect(Plot_Code, input$map_subunit),
#                 Sample_Year %in% input$map_year) %>%
#   left_join(df_genus) %>%
#   dplyr::group_by(!!as.name(input$map_spgroup)) %>%     #either group by plant code or by a group of selected genuses????
#   dplyr::summarize(tree_obs = n()) %>%
#   ungroup() %>%
#   top_n(7, tree_obs) %>%
#   droplevels(.)
# 
# 
# woodymptop_species <- df_treesunits %>%
#                         distinct(!!as.name(input$map_spgroup)) %>%  # use !!as.name to refer to the column
#                         pull()
# 
# woodymptop_species <- as.character(c(as.character(woodymptop_species), "Other", "Sum"))
# 
# spdiv <- df_spdiv %>%
#   left_join(df_genus) %>%
#   dplyr::mutate(Subunit_Code = substr(Plot_Code, 1, 4)) %>%
#   dplyr::mutate(Plot_Genus = forcats::fct_other(Genus,
#                                                    keep = woodymptop_species, ### this could be an input
#                                                    other_level = 'Other')) %>%
#   dplyr::mutate(Plot_Genus = as.character(Plot_Genus)) %>%
#   dplyr::mutate(Genus = case_when(
#     Plant_Code == "Sum" ~ "Sum",
#     TRUE ~ Genus )) %>%
#   dplyr::mutate(Plot_Genus = case_when(
#     Plant_Code == "Sum" ~ "Sum",
#     TRUE ~ Plot_Genus)
#   ) %>%
#   dplyr::mutate(Plot_Genus = as.factor(Plot_Genus)) %>%
#   dplyr::group_by(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, Plot_Genus) %>%
#   dplyr::summarise(Count = sum(Count)) %>%
#   ungroup()
# 
# # rv$spcomp <- spcomp # save spdiv is the equivalent into a reactive format
# # rv$spdiv <- spdiv
# 
# df_mapwide <- spdiv %>%
#   tidyr::pivot_wider(
#     names_from = Plot_Genus,
#     values_from = Count) %>%
#   dplyr::select(Subunit_Code, Plot_Code, Sample_Year, Growth_Form, sort(setdiff(tidyselect::peek_vars(), "Other")), Other)
# 
#   # dplyr::select(-Other, Subunit_Code, Plot_Code, Sample_Year, sort(tidyselect::peek_vars())) # I'm worried about the select -Other
# 
# df_mapspdiv  <- df_mapwide %>%
#    dplyr::filter(Growth_Form == input$size_class)

```


#figuring out how to get random groupings of species/genera




```{r}
df_maplocation <- location  %>% 
  dplyr::select(-Park_Code) %>% #for some reason people want park code
  dplyr::mutate(PlotNum = substr(Plot_Code, 5, 10)) #------ PlotNum doesn't work for all networks

df_treedivmap <- left_join(df_mapspdiv, df_maplocation)

# rv$df_treedivtbl <- df_treedivmap %>%  calls to a reactive value
df_treedivtbl <- df_treedivmap %>%
  dplyr::select(Subunit_Code, Plot_Code, PlotNum, Sample_Year, Sum, everything())

df_treedivmap %<>%
  dplyr::filter(!is.na(Latitude)) %>%
  dplyr::filter(!is.na(Longitude)) %>%
  replace(is.na(.), 0) %>%
  filter(Sample_Year %in% input$map_year) %>%
  dplyr::select(sort(names(.))) %>%
  dplyr::select(-Other, everything()) #new code to order genus alphabetically doesn't do it,  why do I want this alphabetically???



park_zoom <- location %>%
  dplyr::filter(Subunit_Code == input$map_subunit)

bc = leaflet::leaflet(data = mp_compboundary) %>%
  addTiles() %>%
  addPolygons(data = mp_compboundary, color = ~ "black")
```


```{r}
okabe_ito <- c("#0072B2", "#D55E00", "#009E73", '#99DDFF', 
                '#332288', '#882255', '#FFAABB', "#F0E442")

# Define the columns you want to include in the pie chart (e.g., 'Category_A', 'Category_B', 'Category_C')


columns_to_include <- df_treedivmap %>%
  dplyr::select(-c(Subunit_Code, Growth_Form, Plot_Code, PlotNum, Sample_Year, Latitude, Longitude, Sum)) %>%
  # -Other, sort(tidyselect::peak(vars())))
  dplyr::select(Other, everything()) %>%
  colnames()

# Ensure the number of colors matches the number of columns
color_palette <- okabe_ito[1:length(columns_to_include)]

color_palette[length(color_palette)] <- "#333333"

color_palette

```


```{r}
bc <- bc %>%
    addCircleMarkers(data = df_treedivmap,
               lng = ~Longitude,
               lat = ~Latitude,
               labelOptions = labelOptions(noHide = F),
               layerId = ~Plot_Code,
               group = "Markers"
    ) %>%
    addMinicharts(df_treedivmap$Longitude, #########CHANGE DATA
                  df_treedivmap$Latitude,
                chartdata = dplyr::select(df_treedivmap, -c(Subunit_Code, Growth_Form, Plot_Code, PlotNum, Sample_Year, Latitude, Longitude, Sum)),
                # , -Other, sort(tidyselect::peak(vars()))), #trying to order alphabetically
    type = "pie",
    width = sqrt(df_treedivmap$Sum) * 200, #### this might change totally
    col = color_palette, #Okabe_Ito,
    showLabels = F,
    ) %>%
  addLabelOnlyMarkers(df_maplocation$Longitude,
                      df_maplocation$Latitude,
                      label =  df_maplocation$PlotNum,
                      labelOptions = labelOptions(noHide = T, direction = 'top', textOnly = T, style=list('color'="#000000", 'fontSize'="18px"))) %>%
    addScaleBar(position = "bottomright") %>%
  fitBounds(min(park_zoom$Longitude), min(park_zoom$Latitude), max(park_zoom$Longitude), max(park_zoom$Latitude)) %>%
    addLayersControl(
      overlayGroups = c("Markers"), 
      options = layersControlOptions(collapsed = FALSE)

    )

cat("Line4")


 rv$bc <- bc

 
# saveRDS(isolate(reactiveValuesToList(input)), paste0("bc_input.RDS"))
# saveRDS(isolate(reactiveValuesToList(rv)), paste0("bc_rv.RDS"))
# 
# })
# })

click_marker <- eventReactive(input$leaflet_marker_click, {
  # withProgress(message = "Just a moment", detail = "creating proptional stacked barchart...", value = 0, { 


 site <- input$leaflet_marker_click

 return(site$id)
 
cat("line1453")
})
```
```{r testing how to link colors!!!! THIS ONE WORKS}

# df_mapwide instead of df_treedivmap same wide format thoughhhh
# chardata_long <- df_treedivmap
chartdata_long <- df_mapwide %>%
   dplyr::filter(Plot_Code == "COWP013", ########## SHOULD BE click_marker(), ,#
                Sample_Year %in% input$map_year) %>%
  dplyr::select(Sample_Year, Growth_Form, all_of(columns_to_include)) %>%
  tidyr::pivot_longer(cols = all_of(columns_to_include), 
                      names_to = "Plot_Genus", 
                      values_to = "Count") %>%
  replace(is.na(.), 0)


columns_to_include2 <- c(setdiff(columns_to_include, "Other"), "Other")

# Print the reordered vector to confirm
print(columns_to_include2)

color_palette

nn <- setNames(color_palette, columns_to_include2)
 
colors <- columns_to_include2
  
# sort(unique(chartdata_long$Plot_Genus))
  
  
chartdata_long$Plot_Genus <- factor(chartdata_long$Plot_Genus, levels = columns_to_include2)

# Check the levels to confirm the order
levels(chartdata_long$Plot_Genus)

# # unique(slevels$Plot_Genus)
# num_colors <- nlevels(slevels$Plot_Genus)
# okabepalette <- color_pallete_function(num_colors)
# okabepalette <- setNames(okabepalette, levels(slevels$Plot_Genus))
# 
# okabepalette["Other"] <- "#333333"
# 
# cat("Line324")

# colors <- sort(unique(slevels$Plot_Genus)) #new new new still trying to get rid of sum
  
chartdata_long %>%
  # dplyr::filter(Plot_Code == "COWP013", ########## SHOULD BE click_marker(), ,#
  #               Sample_Year %in% input$map_year) %>%
  ggplot(aes(x = Growth_Form, y = Count, fill = Plot_Genus)) +
  geom_bar(width = 0.45, 
           position = "fill",
           stat = "identity") +
  theme_clean() +
  # labs(x = "", y = "Proportion of genera", title = paste0("", input$size_class, ", ", input$map_year, ", ", click_marker())) + # paste0("", input$prop_year, ", ", input$Individual_Unit, ", ", input$Association))
  scale_x_discrete(limits = positions) +
    scale_fill_manual(values = nn[colors],
#scale_fill_manual(values = okabepalette[unique(rv$spcomp$Plot_Genus)],
                      drop = TRUE) 
```

```{r}
renderUI({
  shiny::req(!is.null(rv$df_treedivtbl), !is.null(click_marker), !is.null(input$mp_nativeunit), !is.null(input$map_year))
  
  # rv$comptable <- rv$df_treedivtbl %>%
divtable <- df_mapwide %>% #df_treedivtbl %>%
    dplyr::select(-Sum) %>%
    dplyr::filter(
      # Plot_Code = click_marker(),
      Plot_Code == "COWP013",
      Subunit_Code == input$map_subunit,
      Sample_Year %in% input$map_year)
  
  cat("Line44")  

})

```